[project]
name = "smart-water-bottle-display"
version = "0.1.0"
description = "A PyGame-based simulation of a smart water bottle's round display showing water metrics and battery status"
requires-python = ">=3.11"
dependencies = [
    "pygame>=2.6.1",
    "slack-sdk>=3.34.0",
]